eikona_tessa_media_preview:
    path: /show/{assetId}
    defaults: { _controller: EikonaTessaConnectorBundle:MediaFile:preview }
    methods: [GET]
eikona_tessa_media_detail:
    path: /detail/{assetId}
    defaults: { _controller: EikonaTessaConnectorBundle:MediaFile:detail }
    methods: [GET]
eikona_tessa_media_gallery_product:
    path: /gallery/product/{id}
    defaults: { _controller: EikonaTessaConnectorBundle:MediaFile:productGallery }
    methods: [GET]
eikona_tessa_media_gallery_productmodel:
    path: /gallery/product-model/{id}
    defaults: { _controller: EikonaTessaConnectorBundle:MediaFile:productmodelGallery }
    methods: [GET]
eikona_tessa_media_select:
    path: /select/{data}
    defaults: { _controller: EikonaTessaConnectorBundle:MediaFile:select }
    methods: [GET]
