services:
    eikona.tessa:
        class: 'Eikona\Tessa\ConnectorBundle\Tessa'
        arguments:
            - '@oro_config.global'
            - '@kernel'
            - '@logger'
            - '@eikona.tessa.normalizer.tessa_queue'

    eikona.utilities.math:
        class: Eikona\Tessa\ConnectorBundle\Utilities\Math

    eikona.utilities.id_prefixer:
        class: Eikona\Tessa\ConnectorBundle\Utilities\IdPrefixer

    eikona.tessa.connector.provider.field.mam:
        class: Eikona\Tessa\ConnectorBundle\Enrich\Provider\Field\MamFieldProvider
        tags:
            - { name: pim_enrich.provider.field, priority: 90 }

    eikona.tessa.auth_guard:
        class: 'Eikona\Tessa\ConnectorBundle\Security\AuthGuard'
        arguments:
            - '@eikona.tessa'
            - '@eikona.utilities.math'
            - '@logger'

    eikona.tessa.external_api.serializer.normalizer.product:
        class: Eikona\Tessa\ConnectorBundle\Normalizer\ExternalApi\ProductNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.product'
            - '@pim_api.repository.attribute'
            - '@router'
            - '@request_stack'
            - '@eikona.utilities.id_prefixer'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 91 }

    eikona.tessa.external_api.serializer.normalizer.product_model:
        class: Eikona\Tessa\ConnectorBundle\Normalizer\ExternalApi\ProductNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.product_model'
            - '@pim_api.repository.attribute'
            - '@router'
            - '@request_stack'
            - '@eikona.utilities.id_prefixer'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 91 }

    eikona.tessa.external_api.serializer.normalizer.channel:
        class: Eikona\Tessa\ConnectorBundle\Normalizer\ExternalApi\ChannelNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.channel'
            - '@request_stack'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 91 }

    eikona.tessa.external_api.serializer.normalizer.category:
        class: Eikona\Tessa\ConnectorBundle\Normalizer\ExternalApi\CategoryNormalizer
        arguments:
            - '@pim_catalog.normalizer.standard.category'
            - '@request_stack'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 91 }

    eikona.tessa.notification_queue.service:
        class: Eikona\Tessa\ConnectorBundle\Services\TessaNotificationQueueService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@eikona.tessa'
